### ISSUE TITLE
Error: listen EADDRINUSE: address already in use 127.0.0.1:8080

### ISSUE THREAD

**Issue by sigma-libra** [kotlin-hands-on/web-app-react-kotlin-js-gradle#12]
When running with the command .`/gradlew run` on an Ubuntu 20.04 environment, the following error occurs:

```
> Task :browserDevelopmentRun
✖ ｢wds｣:  Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
✖ ｢wds｣:  Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
```

The process seems to be the only one running on this port, and attempts to get rid of any other processes using port 8080 (sudo kill -9 sudo lsof -t -i:8080, killall node, etc...) have no effect. Changing the port using a .env file with `port=40001` (or any other port) does not change the error.

**Comment by sigma-libra** [comment]
Update: this PR seems to solve the issue: https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle/pull/11. Would be great if it could be merged at some point.

**Comment by SebastianAigner** [comment]
Closing this since #11 has been addressed. If any issues reoccur, feel free to open a new issue :)
