### ISSUE TITLE
Build is very slow

### ISSUE THREAD

**Issue by larzknoke** [kotlin-hands-on/web-app-react-kotlin-js-gradle#14]
Hi,

the build time after every change take up to 20-30 seconds. Is this normal? 

![Bildschirmfoto 2021-09-21 um 23 08 01](https://user-images.githubusercontent.com/6797960/134247970-b94a5878-ee44-4dee-b2c2-2d7b6de5aa7c.png)

`id("org.jetbrains.kotlin.js") version "1.5.0"`
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-bin.zip`
MacBook Pro (13-inch, M1, 2020)

**Comment by SebastianAigner** [comment]
Unfortunately, the build speeds of Kotlin/JS projects still need to be optimized in general – this is not a problem with this specific project. If you feel that your performance is an outlier, you're of course welcome to report it at https://kotl.in/issue, ideally with your reproducer project and setup, and the team will take a look in time.
