### ISSUE TITLE
Tutorial is out of date

### ISSUE THREAD

**Issue by aerialist7** [kotlin-hands-on/web-app-react-kotlin-js-gradle#16]
The Kotlin React tutorial uses the legacy syntax: https://play.kotlinlang.org/hands-on/Building%20Web%20Applications%20with%20React%20and%20Kotlin%20JS/02_Setting_up

**Comment by Leonya** [comment]
@SebastianAigner ping me and I'll guide you through the changes.

**Comment by SebastianAigner** [comment]
Thanks for notifying us – I've [upgraded](https://github.com/kotlin-hands-on/hands-on/commit/398fa83eea1879e17d25a5c9756f25c0ff313d2a) the tutorial to the latest version of Kotlin and the React DSL, the new version will be live soon.
