### ISSUE TITLE
Unresolved reference react

### ISSUE THREAD

**Issue by BrianMwas** [kotlin-hands-on/web-app-react-kotlin-js-gradle#4]
I am getting a unresolved reference react. I have imported all libraries as yours followed all instructions from the kotlin hands on but it can't even see the kotlin html wrapper lib. What's the issue

**Comment by SebastianAigner** [comment]
Since we've overhauled the tutorials from the ground up since this issue was opened, I'm going to close it. If you still run into the same issues, please feel free to open a new issue! :)
