### ISSUE TITLE
run in gradle multiproject layout

### ISSUE THREAD

**Issue by HoffiMuc** [kotlin-hands-on/web-app-react-kotlin-js-gradle#8]
Hi,

I wanna have the react frontend inside a gradle subproject.

To try this out, I cloned this repo and on master branch just

```
mkdir frontend
mv build.gradle.kts frontend/
mv src frontend/
```

added an `include("frontend")` to `settings.gradle.kts`

and altered index.html to have script src adjusted to `<script src="confexplorer-frontend.js"></script>` 

as now the `./build/js` and its `./build/js/packages/confexplorer-frontend/webpack.config.js`
are somewhere else as the `contentBase` which now seems to be `./frontend/build/processedResources/js/main`

the browser gives a 404 not finding the `<script src="confexplorer-frontend.js"></script>` anymore.

is gradle `plugins { id("org.jetbrains.kotlin.js") version "1.4.0" }`  not suited to be used in a multi-project layout?

or is there a standard way to adjust things in the subproject's `build.gradle.kts` ?

or am I basically doing something wrong here?

thanx for support!

EDIT

upgraded dependencies, but same result:

```
plugins {
    id("org.jetbrains.kotlin.js") version "1.4.21"
}

...
dependencies {
    implementation(kotlin("stdlib-js"))

    //React, React DOM + Wrappers (chapter 3)
    implementation("org.jetbrains:kotlin-react:17.0.0-pre.132-kotlin-1.4.21")
    implementation("org.jetbrains:kotlin-react-dom:17.0.0-pre.132-kotlin-1.4.21")
    implementation(npm("react", "17.0.0"))
    implementation(npm("react-dom", "17.0.0"))

    //Kotlin Styled (chapter 3)
    implementation("org.jetbrains:kotlin-styled:5.2.0-pre.132-kotlin-1.4.21")
    implementation(npm("styled-components", "~5.2.1"))
    implementation(npm("inline-style-prefixer", "~6.0.0"))
...
```

2. EDIT

now also did a

`mv frontend/src/main frontend/src/jsMain`

and using this pure multiplatform `build.gradle.kts` but still same results:

```kotlin
plugins {
    kotlin("multiplatform") version "1.4.21"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    maven { setUrl("https://dl.bintray.com/kotlin/kotlin-eap") }
    maven("https://kotlin.bintray.com/kotlin-js-wrappers/")
    mavenCentral()
    jcenter()
}

kotlin {
    js {
        browser {}
        binaries.executable()
    }

    sourceSets {
        val jsMain by getting {
            dependencies {
                implementation(kotlin("stdlib-js"))
            
                //React, React DOM + Wrappers (chapter 3)
                implementation("org.jetbrains:kotlin-react:17.0.0-pre.132-kotlin-1.4.21")
                implementation("org.jetbrains:kotlin-react-dom:17.0.0-pre.132-kotlin-1.4.21")
                implementation(npm("react", "17.0.0"))
                implementation(npm("react-dom", "17.0.0"))
            
                //Kotlin Styled (chapter 3)
                implementation("org.jetbrains:kotlin-styled:5.2.0-pre.132-kotlin-1.4.21")
               implementation(npm("styled-components", "~5.2.1"))
                implementation(npm("inline-style-prefixer", "~6.0.0"))
            
                //Video Player (chapter 7)
                implementation(npm("react-player", "~2.6.0"))
          
                //Share Buttons (chapter 7)
                implementation(npm("react-share", "~4.2.1"))
            
                //Coroutines (chapter 8)
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9")
            }
        }
    }
}
```

**Comment by SebastianAigner** [comment]
Hey @HoffiMuc – sorry for the delay and happy 2021. I've just tried to do the same thing as you – moving the `src` and `build.gradle.kts` to a `frontend` subfolder and adding the respective `include` to the `settings.gradle.kts` file. However, I can run `browserDistribution` in the subproject just fine, and get valid output in the `frontend/build/distributions` file. Is this not what you're expecting? Or do you have a different question?

**Comment by SebastianAigner** [comment]
We do have a dedicated tutorial on how to combine backend and frontend code in the same Gradle project here: https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle :)
